export const ALL_SUBJECTS_DATA = [
  "Maths",
  "Physics",
  "Chemistry",
  "Biology",
  "History",
  "Geography",
  "English",
  "Computer science",
  "Art",
  "Music",
  "Sports",
  "Literature",
  "Philosophy",
  "Economics",
  "Business",
  "Law",
  "Medicine",
  "Psychology",
  "Sociology",
  "Entrepreneurship",
  "Accounting",
  "Fashion",
  "Design",
  "Photography",
  "Film making",
  "French",
  "German",
  "Italian",
  "Spanish",
  "Japanese",
  "Chinese",
  "Korean",
  "Mobile development",
  "Web development",
  "Software development",
  "Data science",
  "Machine learning",
  "Artificial intelligence",
  "Blockchain",
  "Cryptocurrency",
  "Cybersecurity",
  "Data analysis",
  "Data visualization",
  "Political Science",
  "Business Management",
  "Marketing",
  "Finance",
];
